version: '3'
services:
  api:
    build: ./backend/
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/api
    ports:
      - 3004:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: mysql:8.2.0
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - my-mate-db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
      TZ: "Asia/Tokyo"
    ports:
      - "3308:3306"
  front:
    build: ./frontend/
    volumes:
      - ./frontend/app:/front
    ports:
      - 3003:3000
    # gitでnode_modulesを管理していないので、clone後はpackage.jsonに基づいて
    # npm installでpackageをインストールする必要がある
    # command: sh -c "npm install && npm run dev"
    command: sh -c "npm run dev"
    tty: true
    stdin_open: true
  
volumes:
  my-mate-db-volume:
